### ISSUE TITLE
Interaction problem with drawing objects at IE9

### ISSUE THREAD

**Issue by TheSntXel** [ScanEx/gmxDrawing#2]
Can't edit and get sizes of objects (polygons, lines) drawed at map by gmxDrawing tool. 
IE11 in emulate IE9 mode.

**Comment by OriginalSin** [comment]
Can you give any example?

**Comment by TheSntXel** [comment]
Open in IE9 http://scanex.github.io/gmxDrawing/examples/gmxDrawing.html
Try to change drawing objects or get line length and polygon square.

**Comment by OriginalSin** [comment]
Fixed by commit 10048155d1688c9ec07613524a68118b2e1e2ff1
